"""Add index on company.owner_id for performance

Revision ID: add_company_owner_id_index
Revises: 3625d302da7b
Create Date: 2025-01-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_company_owner_id_index'
down_revision = '3625d302da7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_company_owner_id', 'company', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_company_owner_id', table_name='company')
    # ### end Alembic commands ###